sitePjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="sign up"),
    path('logout/', views.logout_view, name="logout"),
    path('author/profile/<str:author_id>/', views.ProfileView.as_view(), name='view profile'),
]

sitePjt/api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    #path('register/', views.create_author, name='create author'),
    #Visibility Private and Public 
    #TO Test: Friends and FOAF
    path('posts', views.view_public_post, name='view public posts'), #OK GET 
    path('posts/<str:post_id>', views.view_single_post, name='view single post'),#OK GET POST
    path('posts/<str:post_id>/comments', views.handle_comments, name='handle comments'), #OK GET POST
    path('author/posts', views.handle_auth_posts, name='handle authenticated posts'), #OK GET POST
    path('author/<str:author_id>/posts', views.view_author_posts, name='view author posts'),#OK GET (POST Json)
    path('author/<str:author_id>', views.ViewProfile, name='view profile'), #OK  GET (POST form)
    path('author/<str:author_id>/friends', views.get_friendlist, name='get friend list'), #OK 
    path('author/<str:author1_id>/friends/<path:author2_id>', views.check_friendship, name='check friendship'), #OK
    path('friendrequest', views.make_friendRequest, name='make friend request'), #OK (POST)
]

sitePjt/friendship/urls.py
from django.urls import path
from . import views

app_name = 'friendship'

urlpatterns = [
    path('author/<str:author_id>/friends/', views.GetFriendsListView.as_view(), name='get friends list'),
    path('friends/', views.GetFriendsView.as_view(), name='get friends list'),
    path('friendrequest/', views.SendFriendRequestView.as_view(), name='friend request'),
    path('friendrequest/accept/', views.HandleRequestView.as_view(), name='handle request'),
    path('friendrequest/unfriend/', views.DeleteFriendView.as_view(), name='delete friend'),
    path('friendrequest/<str:author_id>/', views.FriendsRequestView.as_view(), name='view friend request'),
]

sitePjt/posting/urls.py
from django.urls import path
from . import views as APIviews
app_name = 'posting'

urlpatterns = [
    path('posts/', APIviews.ViewPublicPosts.as_view(), name='view public posts'),
    path('posts/<str:post_id>', APIviews.ViewPostDetails.as_view(), name='view post details'),
    path('posts/<str:post_id>/delete', APIviews.DeletePost.as_view(), name='delete post'),
    path('posts/<str:post_id>/edit', APIviews.EditPost.as_view(), name='edit post'),
    path('posts/<str:post_id>/comments', APIviews.CommentHandler.as_view(), name='comment handler'),
    path('posts/<str:post_id>/comments/<str:comment_id>', APIviews.CommentHandler.as_view(), name='comment handler'),
    path('author/<str:author_id>/posts', APIviews.ViewUserPosts.as_view(), name='view user posts'),
]

sitePjt/sitePjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from . import views
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='200OK API')

urlpatterns = [
    path('', views.ViewHomePage, name='home page'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posting.urls')),
    path('', include('friendship.urls')),
    path('service/', include('api.urls')),
    path('swagger-docs/', schema_view),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitePjt/posting/models.py
from django.db import models
from accounts.models import Author
import uuid
from django.conf import settings
from markdown2 import markdown
POST_VISIBILITY = (
    ('PUBLIC', 'Public'),
    ('PRIVATE', 'Prviate to self'),
    ('FRIENDS', 'Private to friends'),
    ('FOAF', 'Private to friends of friends'),
    ('SERVERONLY', 'Private to local friends'),
)
CONTENT_TYPE = {
    ('text/plain', 'Plain text'),
    ('text/markdown', 'Markdown'),
    ('image/png;base64', 'Image/png'),
    ('image/jpeg;base64', 'Image/jpeg'),
    ('application/base64', 'Application'),
}
CONTENT_TYPE_COMMENT = {
    ('text/plain', 'Plain Text'),
    ('text/markdown', 'Markdown'),
}

UNLISTED = {
    (True, 'True'),
    (False, 'False'),
}

'''
    namely a Post model, belong to author
'''
class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, max_length=50, editable=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    contentType = models.CharField(max_length=20, default = 'text/plain', choices=CONTENT_TYPE)
    #TODO: Update origin url
    origin = models.CharField(default="",max_length=200, editable=False)
    source = models.CharField(max_length=200, blank=True)
    content = models.TextField()
    categories = models.CharField(max_length=200, blank=True)
    unlisted = models.BooleanField(default=False, choices=UNLISTED)
    published = models.DateTimeField('date posted', auto_now_add=True, blank=True)
    visibility = models.CharField(max_length=10, default = 'PUBLIC', choices=POST_VISIBILITY)
    visibleTo = models.TextField(blank=True)
    #visibleTo: field: array of author

    def __str__(self):
        return super().__str__() + "    ------      " +self.title
    
    def content_markdown(self):
        return markdown(self.content,extras=['fenced-code-blocks'])
    
'''
    namely a Comment model, belong to author and post
'''    
class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    contentType = models.CharField(max_length=20, default = 'text/plain', choices=CONTENT_TYPE_COMMENT)
    comment = models.CharField(max_length=288)
    published = models.DateTimeField('date posted', auto_now_add=True, blank=True)

    def comment_markdown(self):
        return markdown(self.comment,extras=['fenced-code-blocks'])
    

sitePjt/posting/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
        )
    )
    image = forms.ImageField(required=False)
    title = forms.CharField(
        widget=forms.TextInput(
        )
    )
    categories = forms.CharField(
        required=False,
        widget =forms.TextInput(
        )
    )
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'contentType',
            'categories',
            'visibility',
            'unlisted',
            'image',
            'visibleTo',
        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'comment',
        ]
    

sitePjt/posting/views.py
from django.shortcuts import render, reverse, redirect
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)
from django.contrib.auth import get_user_model
from django.conf import settings
from .forms import PostForm
from .models import Post, Comment
from accounts.models import ServerNode
from .helper_functions import getVisiblePosts, getRemotePublicPosts, getRemotePostComment, getRemotePost, getRemoteAuthorPosts, postRemotePostComment, getRemoteFOAFPost
from friendship.helper_functions import checkVisibility, getAllFriends
from .serializers import PostSerializer, CommentSerializer
from accounts.permissions import IsActivated, IsActivatedOrReadOnly, IsPostCommentOwner
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseServerError, HttpResponseNotAllowed, HttpResponseForbidden
import base64
from rest_framework.renderers import JSONRenderer

Author = get_user_model()


class ViewPublicPosts(APIView):
    """
    View to  a list of public posts, checking visibility before display to user

    * Requires token authentication.
    * Only activated users are able to read-only this view.
    """
    permission_classes = [IsActivatedOrReadOnly]
    def get(self, request, format=None):
        """
        Return a list of all public posts.
        """
        try:
            posts = getVisiblePosts(request.user)
            posts.sort(key=lambda x: x.published, reverse=True)
            context = {
                'post_list': posts[:100],
            }
            return render(request, "posting/stream.html", context)
        except Exception as e:
            print(e)
            return HttpResponseServerError(e)

    def post(self, request, format=None):
        try:
            form = PostForm(request.POST, request.FILES)
            print(request.POST)
            if form.is_valid():
                form_data = form.cleaned_data
                contentType = form_data.get('contentType')
                if contentType in ['image/png;base64', 'image/jpeg;base64', 'application/base64']:
                    form_data['content'] = base64.b64encode(
                        request.FILES['image'].read()).decode("utf-8")
                form_data['author'] = request.user
                form_data.pop('image')
                newpost = Post.objects.create(**form_data)
                newpost.origin = "{}posts/{}".format(
                    settings.HOSTNAME, str(newpost.id))
                response = PostSerializer(newpost).data
                return JsonResponse(response, status=200)
            else:
                return HttpResponseForbidden("Invalid Input")
        except Exception as e:
            print(e)
            return HttpResponseServerError(e)


class ViewPostDetails(APIView):
    """
    View to a list a detail of post and its comments in the system.

    * Requires token authentication.
    * Only authenticated authors are able to access this view.
    """

    permission_classes = [IsAuthenticated]

    def get(self, request, post_id, format=None):
        """
        Return a detail of post by given Post Id.
        """
        post = Post.objects.filter(id=post_id)
        #Remote request
        if not post.exists():
            nodes = ServerNode.objects.all()
            if nodes.exists():
                post, comments = getRemotePost(post_id, nodes, request.user.url)
            if not post:
                friends_obj = getAllFriends(request.user.id)
                friends = []
                for obj in friends_obj:
                    friends.append(obj.url)
                nodes = ServerNode.objects.all()
                if nodes.exists():
                    for node in nodes:
                        post, comments = getRemoteFOAFPost(
                            node, post_id, request.user, friends)
                        if post:
                            print(post.author)
                            break
            if not post:
                return HttpResponseNotFound("Post not found")
        #Local request
        else:
            post = post[0]
            if not checkVisibility(request.user.url, post):

                return HttpResponseForbidden("You don't have visibility.")
            comments = Comment.objects.filter(post=post)
        context = {
            'post': post,
            'comment_list': comments[:10],
        }
        return render(request, "posting/post-details.html", context)


class DeletePost(APIView):
    """
    Delete to a post by given Post ID in the system.

    * Requires token authentication.
    * Only authenticated and its owner author is able to access this view.
    """

    permission_classes = [IsActivated]

    def post(self, request, post_id, format=None):
        """
        Deleting to a post by given Post Id.
        """
        try:
            post = Post.objects.filter(id=post_id)
            if not post.exists():
                return HttpResponseNotFound("Post not found.")
            post = Post.objects.get(id=post_id)
            if request.user.has_perm('owner of post', post):
                post.delete()
            else:
                return HttpResponseForbidden("You must be the owner of this post.")
            return HttpResponseRedirect(reverse('posting:view user posts', args=(request.user.id,)), {})

        except Exception as e:
            return HttpResponseServerError(e)


class EditPost(APIView):
    """
    Edit to a post by given Post ID in the system.

    * Requires token authentication.
    * Only authenticated and its owner author is able to access this view.
    """
    '''
    use POST to resend a form to update an existing post
    '''
    permission_classes = [IsActivated]
    def post(self, request, post_id, format=None):
        """
        Edit a post by given Post Id.
        """
        try:
            form = request.POST.copy()
            try:
                if request.FILES['image']:
                    form['content'] = base64.b64encode(request.FILES['image'].read()).decode("utf-8")
            except Exception as e:
                print("Error when checking if an image is uploaded")
                print(e)

            post = Post.objects.filter(id=post_id)
            if post.exists():
                post = Post.objects.get(id=post_id)
                if request.user.has_perm('owner of post', post):
                    serializer = PostSerializer(post, data=form, context={'author': request.user}, partial=True)
                    if serializer.is_valid():
                        serializer.save()
                        return HttpResponseRedirect(reverse('posting:view user posts', args=(request.user.id,)), {})
                    else:
                        print(serializer.errors)
                        return Response("Save failed. Invalid data",)
                else:
                    return HttpResponseForbidden("You must be the owner of this post.")
            else:
                return HttpResponseNotFound()
        except Exception as e:
            return HttpResponseServerError(e)


class CommentHandler(APIView):
    """
    Create or Delete a comment to a Post to a given Post ID in the system.

    * Requires token authentication.
    * Only authenticated author is able to access this view.
    """


    permission_classes = [IsActivated]
    def post(self, request, post_id, comment_id=None, format=None):
        """
        Create a comment to a given Post Id.
        """
        try:
            post_host = request.POST.get('post_origin', None)
            if post_host:
                post_host = post_host.split('posts/')[0]
            #Target post on remote server
            if post_host and not post_host == settings.HOSTNAME:
                nodes = ServerNode.objects.filter(host_url__startswith=post_host)
                if nodes.exists():
                    post, _ = getRemotePost(post_id, nodes, request.user.url)
                    if not post:
                        friends = []
                        friend_objs = getAllFriends(request.user.id)
                        for obj in friend_objs:
                            friends.append(obj.url)
                        node = nodes[0]
                        post, _ = getRemoteFOAFPost(node, post_id, request.user, friends)
                    if post:
                        remote_comment = Comment(
                            comment=request.POST['comment'], author=request.user, post=post,contentType=request.POST['contentType'])
                        if postRemotePostComment(remote_comment, request.user.url):
                            return HttpResponseRedirect(reverse('posting:view post details', args=(post_id,)), {})
                        else:
                            return HttpResponseForbidden("Remote comment failed.")
                return HttpResponseNotFound("Post Not Found")
            #Target post on local server
            else:
                post = Post.objects.filter(id=post_id)
                if not post.exists():
                    return HttpResponseNotFound("Post not found.")
            post = post[0]
            if not checkVisibility(request.user.url, post):
                return HttpResponseForbidden("You don't have visibility.")

            serializer = CommentSerializer(data=request.POST, context={
                                           'author': request.user, 'post': post})
            if serializer.is_valid(raise_exception=True):
                serializer.save()
                return HttpResponseRedirect(reverse('posting:view post details', args=(post_id,)), {})
            else:
                return Response("Comment save failed. Invalid data")
        except Exception as e:

sitePjt/posting/templates/posting/myPost.html
{% extends 'posting/home.html' %}
{% block shortProfile %}  
    {% if request.user.is_authenticated %} 
        {% include 'posting/profile-card.html' with request=request%}
                   
    {% endif %}     
{% endblock %}

{% block content %}
{% if posts %}
<script>
    document.getElementById("nav-third").innerHTML="Log Out"
    document.getElementById("nav-third").setAttribute("href","{% url 'accounts:logout' %}")
</script>
<ul>
    {% for post in posts %}
        {% include 'posting/post-full-view.html' with post=post %}
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

sitePjt/posting/templates/posting/stream.html
{% extends 'posting/homepage.html' %}

{% block shortProfile %}  
    {% if request.user.is_authenticated %} 
        <div class="short-profile" >
            {% include 'posting/profile-card.html' with request=request %}
        </div>
        <script>
            document.getElementById("nav-third").innerHTML="Log Out"
            document.getElementById("nav-third").setAttribute("href","{% url 'accounts:logout' %}")
        </script>
    {% else %}
        <script>
            document.getElementById("global-home").innerHTML="Sign In"
            document.getElementById("global-home").setAttribute("href","{% url 'accounts:login' %}")
            document.getElementById("nav-third").innerHTML = "Sign Up"
            document.getElementById("nav-third").setAttribute("href", "{% url 'accounts:sign up' %}")
        </script>
    {% endif %}  
{% endblock %}

{% block content %}
    <ul style=" padding: 0; list-style-type: none;"> 
        <div id="newposts"></div>   
    {% if post_list %} 
            {% for post in post_list %}
            <li id="list">
                {% include 'posting/post-inline-view.html' with post=post %}                 
            </li>
            {% endfor %}
        </ul>
    {% else %}
      
    {% endif %}
{% endblock %}

{% block newPost %}
    {% if request.user.is_authenticated %}
    <div style="text-align:center;">
    </div>
    <div class="card" style="width: 600px;">
        <form method="POST" class="post-form" enctype="multipart/form-data" id='post-form'>
            <div class="form-group">
                <input type="text" name="title" placeholder="Enter title" required="" maxlength="50" id="id_title">
            </div>
            <div class="form-group">
                <textarea name="content" cols="50" rows="30" class="textarea form-control" placeholder="What's Happenning?" maxlength="200" required="" id="id_content"></textarea>
                <span id="counter" style="position: relative; bottom: 23px; left: 235px; font-size: small; color:#989898;">200</span>
                <div id="image-upload" style="position: relative; bottom: 23px; left: 235px;">
                    <label for="id_image">
                        <svg class="bi bi-card-image" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 00-.5.5v9a.5.5 0 00.5.5h13a.5.5 0 00.5-.5v-9a.5.5 0 00-.5-.5zm-13-1A1.5 1.5 0 000 3.5v9A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 2h-13z" clip-rule="evenodd"/>
                            <path d="M10.648 7.646a.5.5 0 01.577-.093L15.002 9.5V13h-14v-1l2.646-2.354a.5.5 0 01.63-.062l2.66 1.773 3.71-3.71z"/>
                            <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" clip-rule="evenodd"/>
                        </svg>
                    </label>
                    <input type="file" name="image" accept="image/*" id="id_image" onchange="readURL(this);" style="display: none;">
                </div>
                <script>
                    function limit() {
                            document.getElementById('id_content').onkeyup = function (event) {
                                count = 200 - document.getElementById('id_content').value.length;
                                document.getElementById('counter').innerText = count;
                            }

                        }
                    var count;
                    var str = document.getElementById('id_content').value;
                    console.log(str)
                    if (str) {
                        count = 200 - (str.length);
                        document.getElementById('counter').innerText = count;
                        limit();
                    } else {
                        limit();
                    }
                </script>
            </div>
            <div class="form-group" style="margin-top:-60px">
                <div class="btn-group">
                <button type="button" name="categories" data-toggle="collapse" href="#post-form-category-input" role="button" aria-expanded="false" aria-controls="post-form-category-input" class="btn btn-outline-primary btn-sm">Categroy</button>
                </div>
                <div class="btn-group">
                    <select name="contentType" id="id_contentType" class="selectpicker" data-style="btn-outline-primary btn-sm" data-width="120px" tabindex="-98">
                        <option value="image/png;base64">Image/png</option>    
                        <option value="image/jpeg;base64">Image/jpeg</option>  
                        <option value="text/plain" selected="">Plain text</option>
                        <option value="text/markdown">Markdown</option>
                        <option value="application/base64">Application</option>
                      </select>
                </div>
                <div class="btn-group">
                    <select name="visibility" id="id_visibility" class="selectpicker" data-style="btn-outline-primary btn-sm" data-width="fit" tabindex="-98">
                        <option value="PUBLIC" selected="">PUBLIC</option>    
                        <option value="PRIVATE">PRIVATE</option>
                        <option value="FRIENDS">FRIENDS</option>
                        <option value="FOAF">FOAFs</option>
                        <option value="SERVERONLY">SERVERONLY</option>
                    </select>
                </div>
                <div class="btn-group">
                    <select name="unlisted" id="id_unlisted" class="selectpicker" data-style="btn-outline-primary btn-sm" data-width="fit" tabindex="-98">
                        <option value="False" selected>Listed</option>
                        <option value="True">Unlisted</option>
                    </select>
                </div>
                <script>
                    let host = "{{ request.user.host }}"
                    let url = host+'friends/'
                    $( document ).ready(function() {
                        $.ajax({
                            url: url,
                            type:'GET',
                            dataType: "json",
                            success: function(data) {
                                let friends = data['friends'];
                                for (let friend of friends){
                                    let f_url = friend['url'];
                                    let f_name = friend['displayName'];
                                    let o =`
                                        <option value="${f_url}">${f_name}</option>
                                    `;
                                    $("#id_VisibleTo").append(o);
                                }
                                $("#id_VisibleTo").selectpicker("refresh");
                            }
                        });
                        
                    });
                </script>
            </div>
            <div class="form-group">
                <div class="collapse" id="post-form-category-input" style="margin-top: 10px;margin-left: 50px;">
                    <input type="text" name="categories" class="form-control" style="width:500px;" placeholder="Enter categories,spread by #" id="id_categories">
                </div>
            </div>
            <div class="btn-group">
                <select name="visibleTo" id="id_VisibleTo" multiple class="selectpicker" data-style="btn-outline-primary btn-sm" data-width="fit" tabindex="-98">
                    <option selected disabled hidden value="none">Visible To</option>
                </select>
            </div>
            <div>
                <img id="blah" src="#" class="mx-auto" style="display: none;"/>
                <script>
                       function readURL(input) {
                        if (input.files && input.files[0]) {
                            var reader = new FileReader();

                            reader.onload = function (e) {
                                $('#blah')
                                    .attr('src', e.target.result)
                                    .width(150)
                                    .attr('style',"display: block;")
                                    .height(200);
                            };
                            reader.readAsDataURL(input.files[0]);
                        }
                    }
                </script>
            </div>
            <div style="margin-top:10px;">
                <input type="submit" value="Post" id='post-form-btn-submit' class="btn btn-primary float-right" style="width: 80px;margin-right: 10px;margin-bottom: 10px;">
                <input id='cancel_btn' type="button" name="clear" class="btn btn-danger float-right" value="Cancel" style="margin-right: 5px;">
            </div>
        </form>
        <script>
        $(document).on('submit', '#post-form',function(e) {
            console.log("Form Sent");
            e.preventDefault(); 
            var file = document.querySelector('input[type=file]');
            var formData = new FormData();
            formData.append('title',$('#id_title').val().trim());
            formData.append('content',$('#id_content').val().trim());
            formData.append('visibility',$('#id_visibility').val().trim());
            formData.append('contentType',$('#id_contentType').val().trim());
            formData.append('unlisted',$('#id_unlisted').val().trim());
            formData.append('categories',$('#id_categories').val().trim());
            formData.append('visibleTo',$('#id_VisibleTo').val());
            formData.append('csrfmiddlewaretoken','{{ csrf_token }}');
            if (file.files[0]){
                image = file.files[0];
                formData.append('image',image);
            }
        $.ajax({
                url:'.',
                type: 'POST',
                dataType: 'json',
                data:formData,
                processData: false,
                contentType: false,
                success: function(data) {
                    let id = data['author']['id'];
                    let host =data['author']['host'];
                    let url = host +'accounts/author/profile/'+id.substring(id.lastIndexOf('/') + 1);
                    let displayName = data['author']['displayName'];
                    let title = data['title'];
                    let origin = host + 'posts/' + data['id'];
                    var html = `
                    <div class="card" style="width:600px">
                    <div class="card-body">
                    <img src="https://avatars.dicebear.com/v2/jdenticon/${displayName}.svg" id="imgProfile" style="width: 50px; height: 50px ;border-radius:50%;"/>
                    <a class="text-dark font-weight-bold" style="text-decoration: none; font-size: large; display: inline;" href="${url}">${displayName}</a>
                    <br>
                    <span id="timestamp">  Just now </span>
                    <span class="badge badge-info">Local</span>
                    <div class="card-title">
                        <p style="font-size: larger;">${title}</p></p>
                    </div>
                    <a  class="" href="${origin}" style="font-size: small;" >Read More</a>
                    </div>
                    </div>
                    `;
                    $("#newposts").prepend(html);
                    reset_form();
 
                },
                failure: function(data) {
                    let error_message = 'Got an error dude' + data; 
                    alert(error_message);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    alert(textStatus + jqXHR.responseText);
                }
        });
        });
        
        $('#cancel_btn').click(function(){
            reset_form();
        }); 

        function reset_form(){
            document.getElementById("post-form").reset();
            var image_input = $('#id_image');
            image_input.replaceWith( image_input = image_input.clone( true ) );
            $('#blah').attr('style',"display: none;");

            $("#id_visibility").val('PUBLIC');
            $("#id_visibility").selectpicker("refresh");

            $("#id_contentType").val('text/plain');
            $("#id_contentType").selectpicker("refresh");

            $("#id_unlisted").val('False');
            $("#id_unlisted").selectpicker("refresh");

            $("#id_VisibleTo").val('none');
            $("#id_VisibleTo").selectpicker("refresh");

        };
        </script>
    </div>
    {% endif %}
{% endblock %}

sitePjt/posting/templates/posting/user-post-list.html
{% extends 'posting/homepage.html' %}
{% block shortProfile %}  
    {% if request.user.is_authenticated %} 
        {% include 'posting/profile-card.html' with request=request%}
                   
    {% endif %}     
{% endblock %}

{% block content %}
{% if posts %}
<script>
    document.getElementById("nav-third").innerHTML="Log Out"
    document.getElementById("nav-third").setAttribute("href","{% url 'accounts:logout' %}")
</script>
<ul>
    {% for post in posts %}
        {% include 'posting/post-full-view.html' with post=post %}
    {% endfor %}

</ul>
{% endif %}

{% endblock %}